# django-humans-txt
# Makefile


PHONY: docs clean build register upload create-virtualenv pip-install startproject makemessages compilemessages merge-and-push-all help
MANAGE=$(PWD)/tmp/$(PROJECT_NAME)/manage.py


docs:
	rst2html README.rst > index.html && zip docs.zip index.html

clean:
	deactivate && rm -rf index.html docs.zip build dist django_humans_txt.egg-info tmp

build:
	./setup.py bdist_wheel sdist

register:
	./setup.py bdist_wheel sdist register

upload:
	./setup.py bdist_wheel sdist upload

create-virtualenv:
	virtualenv tmp/.env/

pip-install:
	pip install Django

startproject:
	cd tmp && django-admin.py startproject $(PROJECT_NAME)

makemessages:
	cd $(PROJECT_NAME);\
	for locale in `ls locale`; do\
		$(MANAGE) makemessages --locale=$$locale --extension=py,html,txt;\
	done

compilemessages:
	$(MANAGE) compilemessages

merge-and-push-all:
	git co master && git merge dev && git co dev && git push --all && git push --tags

help:
	@echo "    docs:"
	@echo "        Build docs."
	@echo "    clean:"
	@echo "        Remove useless and autogenerated files."
	@echo "    build:"
	@echo "        Build package."
	@echo "    register:"
	@echo "        Register package on PyPI."
	@echo "    upload:"
	@echo "        Upload package to PyPI."
	@echo "    create-virtualenv:"
	@echo "        Creates virtualenv."
	@echo "    pip-install:"
	@echo "        Install development requirements."
	@echo "    start-project:"
	@echo "        Create temporary django project to harvest and compile messages."
	@echo "    makemessages:"
	@echo "        Harvest translations."
	@echo "    compilemessages:"
	@echo "        Compile translations."
	@echo "    merge-and-push-all:"
	@echo "        Merge dev branch to master and push all commits and all tags."
